### ISSUE TITLE
ImageNet127

### ISSUE THREAD

**Issue by YUE-FAN** [google-research/crest#5]
Very interesting work! I was wondering whether you could also share the ImageNet127 taxonomy or the code for class grouping.  Thanks!

**Comment by YUE-FAN** [comment]
I think I found it :) https://github.com/minyoungg/wmigftl/tree/master/label_sets/hierarchy

**Comment by linzhiqiu** [comment]
are you able to find the experiment code for ImageNet127?

**Comment by YUE-FAN** [comment]
No, I don't think they provided it. I built a down-sampled version of ImageNet127 and benchmarked it at https://github.com/YUE-FAN/CoSSL. If you are interested, I can share my implementation of CReST in PyTorch.

**Comment by martaskrt** [comment]
@YUE-FAN i am interested in seeing your CReST implementation in PyTorch!

**Comment by YUE-FAN** [comment]
Hi, please find it at [train_cifar_fix_crest.py](https://github.com/YUE-FAN/CoSSL/blob/main/train_cifar_fix_crest.py) and [train_cifar_remix_crest.py](https://github.com/YUE-FAN/CoSSL/blob/main/train_cifar_remix_crest.py). In [train_cifar_remix_crest.py](https://github.com/YUE-FAN/CoSSL/blob/main/train_cifar_remix_crest.py), you can find the commands at the beginning for reproducing CReST numbers in [our paper](https://arxiv.org/abs/2112.04564). For FixMatch, we use this repo to generate the numbers in the paper. But you can still check out our implementation as a reference :)

Besides, we are working on a codebase for imbalanced SSL. We have implemented many algorithms including CReST. Now we are running the benchmarks, and the code will be released soon [here](https://github.com/microsoft/Semi-supervised-learning). Please stay tuned :)

Feel free to contact me with  any further questions or details about the PyTorch CReST.
