### ISSUE TITLE
Batch Size of Unlabeled Data

### ISSUE THREAD

**Issue by ZhuoranYu** [google-research/crest#6]
Hi,

Thanks for your great work! I just have a quick question while going through your hyper-parameters. 

In train_and_eval_loop.py, the parameter `unlab_ratio` is set to 1 whereas FixMatch uses a larger ratio like 7. What are the batch sizes used for obtaining the results in the paper? I didn't seem to find any specification of batch sizes in the manucript.

Thanks for your time and enjoy the rest of your day!

Best

**Comment by fyangf** [comment]
If not specified, we use the default value for labeled data, which is 64: https://github.com/google-research/crest/blob/master/train_and_eval_loop.py#L127-L128. Using unlab_ratio = 7, we eventually have batch size of 64 + 64*7 = 512.

**Comment by ZhuoranYu** [comment]
I see. Thanks for the clarification!
